spring:
  #  security:
  #    user:
  #      name: Alex
  #      password: password
  #      roles: User
  datasource:
    url: jdbc:postgresql://localhost:5432/legends
    password: 1007
    username: postgres
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: create



server:
  port: 8083
  address: 0.0.0.0

jwt:
  secret: $KC@RusNYQZag9nIR&EaFiD598Sg5*rinwtKE%CiVLBkj7ZztZ
  expiration: 86400